version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cinemabuff_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 cinema_buff.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST: db
      - DB_NAME: cinemabuff_db
      - DB_USER: postgres
      - DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
