# Generated by Django 5.2.6 on 2026-01-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('critic', 'Critic'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
