# Generated by Django 5.2.6 on 2026-02-01 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='acting_score',
            field=models.IntegerField(default=5, help_text='Rating for acting performance (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='cinematography_score',
            field=models.IntegerField(default=5, help_text='Rating for cinematography (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='overall_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='story_score',
            field=models.IntegerField(default=5, help_text='Rating for story/plot (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(blank=True, help_text='Legacy 1-5 rating (will be migrated to 1-10 scale)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='RatingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ratings', models.IntegerField(default=0)),
                ('user_ratings_count', models.IntegerField(default=0)),
                ('critic_ratings_count', models.IntegerField(default=0)),
                ('weighted_average', models.FloatField(default=0.0)),
                ('user_average', models.FloatField(default=0.0)),
                ('critic_average', models.FloatField(default=0.0)),
                ('story_average', models.FloatField(default=0.0)),
                ('acting_average', models.FloatField(default=0.0)),
                ('cinematography_average', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_stats', to='movies.movie')),
            ],
        ),
    ]
