# Generated by Django 5.2.6 on 2026-02-01 12:35

from django.db import migrations


def migrate_ratings_to_10_scale(apps, schema_editor):
    """Convert existing 1-5 ratings to 1-10 scale and populate detailed scores"""
    Rating = apps.get_model('movies', 'Rating')
    
    for rating in Rating.objects.all():
        if rating.score and not rating.overall_score:
            # Convert 1-5 scale to 1-10 scale
            rating.overall_score = rating.score * 2
            # Set detailed scores to the same value initially
            rating.story_score = rating.overall_score
            rating.acting_score = rating.overall_score
            rating.cinematography_score = rating.overall_score
            rating.save()


def reverse_migrate_ratings_to_10_scale(apps, schema_editor):
    """Reverse migration: convert 1-10 ratings back to 1-5 scale"""
    Rating = apps.get_model('movies', 'Rating')
    
    for rating in Rating.objects.all():
        if rating.overall_score:
            # Convert 1-10 scale back to 1-5 scale
            rating.score = round(rating.overall_score / 2)
            rating.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating_acting_score_rating_cinematography_score_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_ratings_to_10_scale, reverse_migrate_ratings_to_10_scale),
    ]
