# Generated by Django 5.2.6 on 2026-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_migrate_ratings_to_10_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'TV Series')], default='movie', max_length=10),
        ),
    ]
